server:
  host: 0.0.0.0
  port: 8080
  basePath: /api/v1
  allowedOrigins:
    - http://localhost:8080
  shutdownTimeout: 5

database:
  type: sqlite3
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: mojito
  sslMode: disable
  timeZone: UTC
  sqlitePath: ./mojito.db

auth:
  secretKey: supersecretkey
  accessTokenExpire: 30
  refreshTokenExpire: 7
  passwordResetExpire: 24
  verificationExpire: 48
  passwordMinLength: 8
  passwordHashCost: 10
  firstSuperuserEmail: admin@example.com
  firstSuperuserPasswd: admin

email:
  enabled: false
  smtpHost: smtp.example.com
  smtpPort: 587
  smtpUser: user
  smtpPasswd: password
  fromEmail: noreply@example.com
  fromName: Mojito App

logging:
  level: info
  file: ""